name: Language Check

on: [ push ]

jobs:
  publish:
        runs-on: Ubuntu-latest
        permissions:
          issues: write
        steps:
          - uses: actions/checkout@v3
          - name: Log into git
            run: |
              set -e
              REPO_FULLNAME=$(jq -r ".repository.full_name" "$GITHUB_EVENT_PATH")
              IFS="/"
              read -a strarr <<< $REPO_FULLNAME
              REPO_SHORTNAME=${strarr[1]}
              IFS=$"\n"
              echo "### Clone git remote..."
              echo $REPO_FULLNAME
              echo "git clone https://$GITHUB_TOKEN@github.com/$REPO_FULLNAME.git"
              git clone https://x-access-token:$GITHUB_TOKEN@github.com/$REPO_FULLNAME.git
              echo "### Getting branch"
              BRANCH=${GITHUB_REF#*refs/heads/}
              echo "### Branch: $BRANCH (ref: $GITHUB_REF )"
              git checkout $BRANCH
              cd $REPO_SHORTNAME
              echo "### Login into git..."
              git config --global user.email "brianharveydev@icloud.com"
              git config --global user.name "bharveactions"
              
          - name: Check Python
            run: |
              if [ "$python" == true ] ;
                then
                    echo "Start python.sh"
                    echo "Install autopep8"
                    pip install autopep8
                    echo "Execute autopep"
                    autopep8 --in-place -r -a -a .
                    echo "End of python.sh"
                    curl --request POST \
                        --url https://api.github.com/repos/${{ github.repository }}/issues \
                        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                        --header 'content-type: application/json' \
                        --data '{
                          "labels":["Python"],
                          "title": "Automated issue for commit: ${{ github.event_name }} the python works",
                          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
                          }' \
                        --fail
                else
                    echo "Python is skipping"
                    curl --request POST \
                        --url https://api.github.com/repos/${{ github.repository }}/issues \
                        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                        --header 'content-type: application/json' \
                        --data '{
                          "labels":["Python failed"],
                          "title": "Automated issue for commit: ${{ github.event_name }} the python doesnt work",
                          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
                          }' \
                        --fail
                fi
  
