name: Language Check

on: [ push ]

jobs:
  publish:
        runs-on: Ubuntu-latest
        permissions:
          issues: write
        steps:
          - uses: actions/checkout@v3
          - name: Check python
            run: |
              if [ "$python" == true ] ;
                then
                    echo "Start python.sh"
                    echo "Install autopep8"
                    pip install autopep8
                    echo "Execute autopep"
                    autopep8 --in-place -r -a -a .
                    echo "End of python.sh"
                    curl --request POST \
                        --url https://api.github.com/repos/${{ github.repository }}/issues \
                        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                        --header 'content-type: application/json' \
                        --data '{
                          "labels":["Python"],
                          "title": "Automated issue for commit: ${{ github.event_name }} the python works",
                          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
                          }' \
                        --fail
                else
                    echo "Python is skipping"
                    curl --request POST \
                        --url https://api.github.com/repos/${{ github.repository }}/issues \
                        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                        --header 'content-type: application/json' \
                        --data '{
                          "labels":["Python failed"],
                          "title": "Automated issue for commit: ${{ github.event_name }} the python doesn't work",
                          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
                          }' \
                        --fail
                fi
  
