name: Swift Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild
    - name: Run tests
      run: xcodebuild test -project BookStore.xcodeproj -scheme BookStoreUITests
      
# TODO: Add secrets and p12 for testflight compat.

